name: macos-latest
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting the Environment Up.
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: source setup.sh "Dec2022" "Dec2022" "$NGROK_AUTH_TOKEN"
    - name: ngrok теперь прослушивает соединения VNC
    - name: IP
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: Данные VNC
      run: source info.sh "decpro" "Dec2022"
    - name: Настройка сеанса tmate
      uses: mxschmitt/action-tmate@v2
